### ISSUE TITLE
Add the possibility to specify a SPARQL endpoint

### ISSUE THREAD

**Issue by cristianvasquez** [reactodia/reactodia-workspace#26]
Thank you for this fantastic library!

Would it be possible to enable users to specify their own SPARQL endpoint? This feature could transform the library into a highly practical, everyday tool.

I understand this is primarily a library, but incorporating endpoint configuration into a playground powered by the library could significantly enhance its usability.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the SparqlExample component to include an input field for users to specify their own SPARQL endpoint URL. The endpoint URL is now stored in state and used when creating the SparqlDataProvider. Also added a simple form to update the endpoint and reload the workspace.

You can review changes in this commit: https://github.com/lkilu6456546/reactodia-reactodia-workspace-26/commit/572dcc14fc626a257f4fba6fcb544ae485a12ebc.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by AlexeyMz** [comment]
@cristianvasquez Thank you for the encouragement!

I think it should be relatively easy and straightforward to implement a simple UI for the playground.
I'll try to add it soon to https://reactodia.github.io demos 😄

P.S. In the meantime, when running examples locally it is possible to specify custom SPARQL endpoint via `SPARQL_ENDPOINT` environment variable like this:
```sh
SPARQL_ENDPOINT=http://example.com/sparql npm run serve
```

**Comment by AlexeyMz** [comment]
@cristianvasquez It's here, on the new playground page: https://reactodia.github.io/playground/sparql

Currently the configuration dialog contains only SPARQL endpoint URL but more options can be easily added to the playground as well.

**Comment by cristianvasquez** [comment]
Oh waw, this is really useful! Thank you for it
